### PR TITLE
Replace default.nix with flake.nix

### PR DESCRIPTION
**Pull request by Mr-Andersen**
With flake.nix it's possible to try grace without cloning repo: `nix run github:Mr-Andersen/grace -- --help`
In addition to this, flake is the new standard

### CODE REVIEW

**Comment by Gabriella439** [comment]
Looks great!  Could you also fix the `shell.nix` to match?  Currently it refers to the deleted `default.nix` file

**Comment by Gabriella439** [comment]
Oh, actually, one more thing: the compiler would need to be parametrizable in order to support the GHCJS build

More generally, these are the workflows we would need to support (updating the `README.md` and `CONTRIBUTING.md` to match any changes):

* Obtain a shell for the default compiler (e.g. ghc 8.10.7)
* Obtain a shell for GHCJS
* Build Grace using the default compiler
* Build the Grace website using GHCJS

**Comment by Mr-Andersen** [comment]
@Gabriella439 weird, I don't get cabal in current nix-shell. Does it work for you? (Is it meant to work?)
```
> nix-shell

[nix-shell:~/Work/cloned/grace]$ cabal
The program 'cabal' is not in your PATH. You can make it available in an
ephemeral shell by typing:
  nix-shell -p cabal-install
```

**Comment by Mr-Andersen** [comment]
This is current state of flake (only x86_64-linux is present here):
```
> nix flake show --allow-import-from-derivation github:Mr-Andersen/grace
github:Mr-Andersen/grace/038e7ab276be0ea8e231313b9bdd5ad2678b2380
├───apps
│   └───x86_64-linux
│       └───default: app
├───devShells
│   └───x86_64-linux
│       ├───ghc8107: development environment 'ghc-shell-for-grace-1.0.0'
│       └───ghcjs: development environment 'ghc-shell-for-grace-1.0.0'
└───packages
    └───x86_64-linux
        ├───grace-ghc8107: package 'grace-1.0.0'
        ├───grace-ghcjs: package 'grace-1.0.0'
        ├───graceNoTests-ghc8107: package 'grace-1.0.0'
        ├───graceNoTests-ghcjs: package 'grace-1.0.0'
        ├───website-ghc8107: package 'try-grace'
        └───website-ghcjs: package 'try-grace'
```
Shells can be opened with `nix develop .#<shell-name>` e.g. `nix develop .#ghc8107`. What concerns me is package naming. Initially I made this structure: `packages."<system>"."<name>"."<compiler>" = derivation`. However, flakes have quite strict [output schema](https://nixos.wiki/wiki/Flakes#Output_schema), and current naming `packages."<system>"."<name>-<compiler>" = derivation` follows it. It's not pretty :) It's automatically generated from `compilers` and `withCompiler` in 111-117 lines. I can use some custom naming, for example, `"grace"` and `"grace-js"` (this won't be easy to generate automatically) or add an "if" for `defaultCompiler` so `"grace-ghc8107"` becomes just `"grace"` and so are other packages (this will elevate `defaultCompiler` among others; will not be backward-compatible). What do you think?

**Comment by Gabriella439** [comment]
I think the layout I would suggest is something like this:

```
├───apps
│   └───x86_64-linux
│       └───default: app
├───devShells
│   └───x86_64-linux
│       ├───default: development environment 'ghc-shell-for-grace-1.0.0'
│       └───ghcjs: development environment 'ghc-shell-for-grace-1.0.0'
└───packages
    └───x86_64-linux
        ├───default: package 'grace-1.0.0'
        └───website: package 'try-grace'
```

In other words:

* Only support two compilers (GHC 8.10.7 and GHCJS)

* Omit the suffix for the non-GHCJS builds

* Make the default devShell the GHC 8.10.7 one

* It's not necessary to export a `graceNoTests` package

  I believe this is only used internally for the `app`, but it doesn't need to be exposed to flake users otherwise
 
* It's not necessary to build the `website` for GHC 8.10.7 (I believe the build would currently fail)

  In theory, we could eventually build the website using GHC 8.10.7 using `jsaddle`, though

* It's not necessary to provide a package for building Grace with GHCJS

  People will likely not use the Grace GHCJS build independently of the website since they are tightly coupled

For the last three points, you can still keep them if it's easier that way.  If you do so, then I'd suggest the `grace` / `grace-js` naming convention you mentioned for distinguishing between non-GHCJS builds and GHCJS builds.  That way if the compiler version changes the package names don't change.

**Comment by Mr-Andersen** [comment]
Seems like all is done

**Review by Gabriella439 — APPROVED** [review]
Looks great!  Thank you for doing all of this 🙂

I'm just waiting for CI to pass

**Pull request merged**
